[package]
name = "cgn_ec_rust_parsers"
version = "0.2.0"
edition = "2024"

[lib]
name = "cgn_ec_rust_parsers"
# "cdylib" is necessary for Python bindings
crate-type = ["cdylib"]

[profile.dev]
overflow-checks = true
lto = false

[profile.release]
lto = true

[dependencies]
pyo3 = { version = "0.21.0", features = ["extension-module"] }
regex = "1.9.1"
rayon = "1.8.0"

[features]
default = ["pyo3/extension-module"]