name: Publish Python 🐍 rust bindings 📦 to PyPI and TestPyPI

on:
  release:
    types: [created]

permissions:
  contents: read

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Build wheels
        uses: PyO3/maturin-action@v1
        with:
          target: ${{ matrix.platform.target }}
          args: --release --out dist -i python3.12
          sccache: ${{ !startsWith(github.ref, 'refs/tags/') }}
      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheels-linux-${{ matrix.platform.target }}
          path: dist

  publish-to-testpypi:
    name: Publish Python 🐍 rust bindings 📦 to TestPyPI
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/') && github.event.release.prerelease == true
    needs: [linux]
    
    permissions:
      id-token: write
      contents: write
      attestations: write
    steps:
      - uses: actions/download-artifact@v4
      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-path: 'wheels-*/*'
      - name: Publish to TestPyPI
        uses: PyO3/maturin-action@v1
        with:
          command: upload
          args: --non-interactive --skip-existing wheels-*/* --repository-url=https://test.pypi.org/legacy/

  publish-to-pypi:
    name: Publish Python 🐍 rust bindings 📦 to PyPI
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/') && github.event.release.prerelease == false
    needs: [linux]
    
    permissions:
      id-token: write
      contents: write
      attestations: write
    steps:
      - uses: actions/download-artifact@v4
      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-path: 'wheels-*/*'
      - name: Publish to PyPI
        uses: PyO3/maturin-action@v1
        with:
          command: upload
          args: --non-interactive --skip-existing wheels-*/*